### ISSUE TITLE
Gradle Dependency

### ISSUE THREAD

**Issue by caitlynoleykowski** [phansier/FlowReactiveNetwork#1]
Hey, is there any way to use this library via a gradle dependency rather than having to import the whole codebase?
I intended to use
    implementation "com.github.andreysber:flowreactivenetwork:1.0.0"
but I see there is no release version.

Thank you

**Comment by AndreySBer** [comment]
@caitlynoleykowski Thank you for interest. There is not yet. I will try to publish it soon.
You can take it as a git submodule or copy and include as a Gradle module now.

**Comment by AndreySBer** [comment]
@caitlynoleykowski I have published the library in bintray. Now you can use it with
`implementation 'ru.beryukhov:flowreactivenetwork:1.0.0'`

**Comment by caitlynoleykowski** [comment]
@AndreySBer Thanks! I've tried to use
`implementation 'ru.beryukhov:flowreactivenetwork:1.0.0'`
in my gradle dependencies but it's not found.
Currently for repositories I have
```
repositories {
        google()
        jcenter()
        mavenLocal()
        maven { url "https://jitpack.io" }
        maven { url 'http://dl.bintray.com/kotlin/kotlin-eap' }
}
```
Do you know if there is something additional I will need to put for repositories so that it can find yours in bintray?

**Comment by AndreySBer** [comment]
@caitlynoleykowski Thanks for your patience. There was a problem with initial publication.
As for the library is not published in JCenter yet, you should temporary add in your repositories:
```
maven {
            url "https://dl.bintray.com/andreyberyukhov/FlowReactiveNetwork"
        }
```
and use the 1.0.2 version.

**Comment by phansier** [comment]
There are plans to publish this library in mavenCentral as soon as one of the issues #5 #9 #10 will be merged.
